FROM mongodb/mongodb-community-server:8.3.4-ubuntu2204

COPY --chown=mongodb:mongodb ./mongo_keyfile /tmp/mongo_keyfile
COPY --chown=mongodb:mongodb ./mongod.conf /etc/mongod.conf
RUN chmod 400 /tmp/mongo_keyfile

CMD ["mongod", "--config", "/etc/mongod.conf"]
