#!/bin/sh

# A hook script to verify that we don't commit files that could contain sensible data or credentials like json, csv, xls(x) or .env

function validate_commit() {

  sensible_files_pattern="\.(csv|xls|xls(x?)|json|env)$"
  exception="(package.json$"
  exception="$exception|manifest.json"
  exception="$exception|sample.json"
  exception="$exception|eslintrc.json|app.json|jsconfig.json"
  exception="$exception)$"
  local files
  files=$(git diff --cached --name-only | grep -v -E "$exception" | grep -E "$sensible_files_pattern") || true

  if [ -z "$files" ]; then
    make lint
  else
    echo
    echo "ERROR: Preventing commit of potentially sensible files:"
    echo
    echo "$files" | sed "s/^/   /"
    echo
    echo "Either reset those files, add them to .gitignore or remove them."
    echo
    echo "If you know what you are doing, please double-check that you are not commiting"
    echo "any credentials, password or sensible data and run git commit again with --no-verify."
    echo
    exit 1
  fi
  cd -
}

validate_commit