import { getDbCollection } from "@/common/utils/mongodbUtils"

const MON_LOGEMENT_ETUDIANT_LINK = `<a href="https://monlogementetudiant.beta.gouv.fr/trouver-un-logement-etudiant?utm_source=labonnealternance&utm_medium=referral&utm_campaign=partenariat_backlink&utm_content=page_ville" target="_blank" rel="noopener noreferrer" class="lba-link-external" aria-label="Consulter le site Mon Logement Étudiant (ouverture dans un nouvel onglet)">Mon Logement Étudiant</a>`

const updates: Array<{ slug: string; logementText: string }> = [
  {
    slug: "bordeaux",
    logementText: `Trouver un logement à Bordeaux <span style="font-weight: bold;color:#0063cb">nécessite une recherche active</span> mais reste accessible pour les alternants avec un budget adapté. Pour un studio, comptez entre 450 et 650 euros charges comprises selon le quartier et l\'état du bien, tandis qu\'un T2 se situe généralement entre 600 et 850 euros.<ul><li>Les quartiers les plus prisés par les étudiants et alternants sont <span style="font-weight: bold;color:#0063cb">la Victoire, Saint-Michel et Capucins</span>, offrant un bon rapport qualité-prix et une ambiance jeune et dynamique.</li><li><span style="font-weight: bold;color:#0063cb">Les Chartrons et Bacalan</span> attirent ceux qui recherchent un cadre plus moderne et rénové, avec des loyers légèrement supérieurs.</li><li><span style="font-weight: bold;color:#0063cb">Bastide</span>, sur la rive droite, propose des logements plus abordables avec un accès direct au centre-ville par le tram.</li></ul><span style="font-weight: bold;color:#0063cb">Il est recommandé de commencer ses recherches au moins deux mois avant la rentrée</span> sur les plateformes classiques (Leboncoin, PAP) et les groupes Facebook dédiés. Rendez-vous sur ${MON_LOGEMENT_ETUDIANT_LINK}, un service public ayant pour objectif de faciliter l\'accès au logement étudiant pour découvrir plus de 300 résidences sociales (soit près de 40000 logements) sur toute la France. Les résidences étudiantes privées constituent une alternative pratique mais souvent plus onéreuse (650-800 euros pour un studio meublé). <span style="font-weight: bold;color:#0063cb">N\'oubliez pas que vous pouvez bénéficier des APL pour réduire votre loyer mensuel</span>. Certains employeurs proposent également une aide au logement dans le cadre du contrat d\'alternance, pensez à vous renseigner. La forte demande locative nécessite de constituer un dossier solide avec garants.`,
  },
  {
    slug: "paris",
    logementText: `Le logement représente le principal défi financier pour les alternants à Paris, avec des loyers parmi les plus élevés de France.<ul><li><span style="font-weight: bold;color:#0063cb">Comptez entre 700€ et 1000€ par mois pour un studio</span> (15-25m²) et entre 1000€ et 1500€ pour un T2, selon l\'arrondissement et l\'état du bien. Les arrondissements périphériques (18e, 19e, 20e, 13e) et les villes limitrophes de petite couronne (Montreuil, Saint-Denis, Ivry, Pantin) offrent des loyers plus abordables tout en restant bien desservis par les transports.</li><li><span style="font-weight: bold;color:#0063cb">Les résidences étudiantes</span> comme les Estudines ou Cardinal Campus proposent des logements meublés avec services, souvent plus chers mais sans les tracas de l\'ameublement. N\'oubliez pas de demander l\'APL (aide personnalisée au logement) qui peut réduire significativement votre loyer de 100 à 250€ selon vos revenus.</li><li><span style="font-weight: bold;color:#0063cb">Les colocations</span> restent une solution populaire pour réduire les coûts et créer du lien social, avec des loyers entre 500€ et 800€ par chambre.</li></ul>Anticipez vos recherches au moins 2-3 mois avant votre arrivée via des plateformes comme Leboncoin, PAP, ou La Carte des Colocs, et préparez un dossier solide avec garant car la concurrence est féroce sur le marché locatif parisien. ${MON_LOGEMENT_ETUDIANT_LINK} est un service public ayant pour objectif de faciliter l\'accès au logement étudiant et référence plus de 300 résidences sociales (soit près de 40000 logements) sur toute la France.`,
  },
  {
    slug: "marseille",
    logementText: `Trouver un logement à Marseille demande de l\'anticipation mais reste plus accessible financièrement qu\'à Paris ou Lyon.<br /><br /><span style="font-weight: bold;color:#0063cb">Pour un studio, comptez entre 400€ et 600€ par mois</span> selon le quartier et l\'état du bien, tandis qu\'un T2 <span style="font-weight: bold;color:#0063cb">se situe généralement entre 550€ et 800€</span>.<br /><br />Les quartiers prisés par les alternants et étudiants incluent le 5ème arrondissement (Baille, Saint-Pierre), le 6ème (Castellane, Vauban, Notre-Dame du Mont) et certains secteurs du 1er et 7ème arrondissements, proches du centre et bien desservis. Le 4ème arrondissement, notamment autour de la Joliette et Euroméditerranée, se développe rapidement avec des logements neufs mais à des prix plus élevés.<br /><br /><span style="font-weight: bold;color:#0063cb">Les résidences étudiantes du CROUS proposent des chambres entre 300€ et 450€</span>, mais les places sont limitées et la demande forte. Consultez ${MON_LOGEMENT_ETUDIANT_LINK}, pour découvrir de nombreux conseils et les logements disponibles dans votre secteur. Plusieurs résidences privées pour étudiants et jeunes actifs (Studéa, Cardinal Campus) offrent des alternatives avec services inclus, à partir de 500€. Il est conseillé de commencer ses recherches dès avril-mai pour une rentrée en septembre, via les plateformes classiques (Leboncoin, SeLoger) et les groupes Facebook dédiés.<br /><br /><span style="font-weight: bold;color:#0063cb">Attention aux arnaques</span> : visitez toujours le logement avant de verser un quelconque acompte. Les aides au logement (APL) peuvent réduire significativement votre loyer, pensez à faire votre demande sur le site de la CAF dès votre installation.`,
  },
  {
    slug: "toulouse",
    logementText: `<span style="font-weight: bold;color:#0063cb">Trouver un logement à Toulouse demande de l\'anticipation, surtout pour les rentrées de septembre où la demande est forte.</span><br /><br />Pour <span style="font-weight: bold;color:#0063cb">un studio, comptez entre 400 et 550 euros</span> charges comprises selon le quartier et l\'état du bien, tandis qu\'un T2 oscille entre 550 et 750 euros, ce qui reste abordable comparé aux grandes métropoles françaises.<ul><li><span style="font-weight: bold;color:#0063cb">Les quartiers les plus prisés par les alternants</span> sont Saint-Michel et Arnaud-Bernard pour leur ambiance jeune et leurs prix encore accessibles, les Carmes pour sa centralité et son charme, ou Compans-Caffarelli pour sa modernité et sa proximité avec le campus universitaire.</li><li><span style="font-weight: bold;color:#0063cb">Les quartiers de Rangueil, Lardenne ou Croix-Daurade offrent des loyers plus modérés</span> tout en restant bien desservis par les transports.</li></ul>Pour faciliter vos recherches, utilisez les plateformes classiques mais aussi les groupes Facebook dédiés au logement étudiant à Toulouse, très actifs. <span style="font-weight: bold;color:#0063cb">Pensez aux résidences étudiantes privées</span> (Studéa, Nexity Studéa) qui proposent des studios meublés avec services, pratiques quand on arrive de l\'extérieur. <span style="font-weight: bold;color:#0063cb">Les résidences CROUS sont une option économique mais très demandée</span>, nécessitant une candidature précoce via le dossier social étudiant. ${MON_LOGEMENT_ETUDIANT_LINK} recense près de 40000 logements répartis dans près de 400 résidences étudiantes à vocation sociale dans 11 régions. L\'offre de logement CROUS (175 000 logements) est également visible sur la plateforme.<br /> En tant qu\'alternant, vous pouvez bénéficier des APL pour réduire votre loyer, et certains employeurs proposent une participation au logement dans le cadre du contrat d\'apprentissage.`,
  },
]

export const up = async () => {
  for (const { slug, logementText } of updates) {
    const result = await getDbCollection("seo_villes").updateOne({ slug }, { $set: { "content.logement.text": logementText } })
    if (result.matchedCount === 0) {
      throw new Error(`Migration 20260323180547-update-seo-ville: no document found for slug "${slug}"`)
    }
  }
}

// set to false ONLY IF migration does not imply a breaking change (ex: update field value or add index)
export const requireShutdown: boolean = false
