const mailType = {
  CANDIDAT_HAVE_YOU_BEEN_CONTACTED: "CANDIDAT_HAVE_YOU_BEEN_CONTACTED",
  CFA_REMINDER_RESEND_APPOINTMENT: "CFA_REMINDER_RESEND_APPOINTMENT",
}

const candidatFollowUpType = {
  CONFIRM: "CONFIRM",
  RESEND: "RESEND",
}

export { mailType, candidatFollowUpType }
