const optMode = {
  OPT_IN: "OPT_IN",
  OPT_OUT: "OPT_OUT",
}

const mailType = {
  OPT_OUT_INVITE: "OPT_OUT_INVITE",
  OPT_OUT_UNSUBSCRIPTION_CONFIRMATION: "OPT_OUT_UNSUBSCRIPTION_CONFIRMATION",
  OPT_OUT_STARTING: "OPT_OUT_STARTING",
  PREMIUM_INVITE: "PREMIUM_INVITE",
  PREMIUM_INVITE_FOLLOW_UP: "PREMIUM_INVITE_FOLLOW_UP",
  PREMIUM_REFUSED: "PREMIUM_REFUSED",
  PREMIUM_STARTING: "PREMIUM_STARTING",
}

export { optMode, mailType }
