# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    mem_limit: 128m
    volumes:
      - lba_nginx_data:/data:z
      - ./reverse_proxy/dev/includes:/etc/nginx/templates/includes/env

  ui:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./ui:/app:z
      - /app/node_modules/
      - /app/.next
    mem_limit: 512m
    stdin_open: true

  ui_espace_pro:
    build:
      args:
        LBA_ENV: dev
    volumes:
      - ./ui_espace_pro:/app:z
      - /app/node_modules/
    env_file: ./ui_espace_pro/.env
    mem_limit: 512m
    stdin_open: true

  server:
    mem_limit: 2g
    build:
      args:
        LBA_ENV: dev
    ports:
      - "9229:9229" # Allows remote debugging
    volumes:
      - lba_server_data:/data:z
      - ./server/src:/app/src:z
    environment:
      - LBA_ENV=dev
      - LBA_LOG_LEVEL=debug

  mongodb:
    image: mongo:5.0.6-focal
    container_name: lba_mongodb
    mem_limit: 5g
    command: --wiredTigerCacheSizeGB 4
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - lba_mongodb_data:/data:z
    networks:
      - lba_network

  elasticsearch:
    mem_limit: 2g
    ports:
      - "9200:9200"
    volumes:
      - lba_elasticsearch_data:/usr/share/elasticsearch/data

  clamav:
    mem_limit: 512m
    ports:
      - "3310:3310"

  smtp:
    image: mailhog/mailhog
    container_name: lba_mailhog
    mem_limit: 128m
    ports:
      - "1025:1025"
    environment:
      - MH_UI_WEB_PATH=smtp
    networks:
      - lba_network

volumes:
  lba_mongodb_data:
    driver: local
    name: lba_mongodb_data
  lba_nginx_data:
    driver: local
    name: lba_nginx_data
  lba_server_data:
    driver: local
    name: lba_server_data
  lba_elasticsearch_data:
    driver: local
    name: lba_elasticsearch_data
