# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - doctrina_nginx_data:/data:z
      - ./reverse_proxy/dev/includes:/etc/nginx/templates/includes/env

  ui:
    build:
      args:
        DOCTRINA_ENV: dev
    volumes:
      - ./ui:/app:z
      - /app/node_modules/
      - /app/.next
    mem_limit: 1g
    stdin_open: true

  ui_espace_pro:
    build:
      args:
        DOCTRINA_ENV: dev
    volumes:
      - ./ui_espace_pro:/app:z
      - /app/node_modules/
    env_file: ./ui_espace_pro/.env
    mem_limit: 1g
    stdin_open: true

  server:
    build:
      args:
        DOCTRINA_ENV: dev
    ports:
      - "9229:9229" # Allows remote debugging
    volumes:
      - doctrina_server_data:/data:z
      - ./server/src:/app/src:z
    environment:
      - DOCTRINA_ENV=dev
      - DOCTRINA_LOG_LEVEL=debug

  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - doctrina_mongodb_data:/data:z

  elasticsearch:
    ports:
      - "9200:9200"
    volumes:
      - doctrina_elasticsearch_data:/usr/share/elasticsearch/data

  clamav:
    ports:
      - "3310:3310"

  smtp:
    image: mailhog/mailhog
    container_name: doctrina_mailhog
    ports:
      - "1025:1025"
    volumes:
      - ./mailhog-auth.txt:/app/mailhog-auth.txt
    environment:
      - MH_UI_WEB_PATH=smtp
      - MH_AUTH_FILE=/app/mailhog-auth.txt
    networks:
      - doctrina_network

volumes:
  doctrina_mongodb_data:
    driver: local
    name: doctrina_mongodb_data
  doctrina_nginx_data:
    driver: local
    name: doctrina_nginx_data
  doctrina_server_data:
    driver: local
    name: doctrina_server_data
  doctrina_elasticsearch_data:
    driver: local
    name: doctrina_elasticsearch_data
