import { PAGES } from "@/utils/routes.utils"

export const IMAGE_BASE_PATH = "/images/guides/guide-alternant/"

export const ARTICLES: Record<string, { id: string; title: string; description: string; imageUrl: string; path: string; updatedAt: string }> = {
  ["decouvrir-l-alternance"]: {
    id: "decouvrir-l-alternance",
    title: PAGES.static.guideAlternantDecouvrirLAlternance.title,
    description: PAGES.static.guideAlternantDecouvrirLAlternance.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}decouvrir-l-alternance.svg`,
    path: PAGES.static.guideAlternantDecouvrirLAlternance.getPath(),
    updatedAt: "30/01/2026",
  },
  ["preparer-son-projet-en-alternance"]: {
    id: "preparer-son-projet-en-alternance",
    title: PAGES.static.guideAlternantPreparerSonProjetEnAlternance.title,
    description: PAGES.static.guideAlternantPreparerSonProjetEnAlternance.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}preparer-son-projet-en-alternance.svg`,
    path: PAGES.static.guideAlternantPreparerSonProjetEnAlternance.getPath(),
    updatedAt: "30/01/2026",
  },
  ["se-faire-accompagner"]: {
    id: "se-faire-accompagner",
    title: PAGES.static.guideAlternantSeFaireAccompagner.title,
    description: PAGES.static.guideAlternantSeFaireAccompagner.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}se-faire-accompagner.svg`,
    path: PAGES.static.guideAlternantSeFaireAccompagner.getPath(),
    updatedAt: "30/01/2026",
  },
  ["la-rupture-de-contrat"]: {
    id: "la-rupture-de-contrat",
    title: PAGES.static.guideAlternantLaRuptureDeContrat.title,
    description: PAGES.static.guideAlternantLaRuptureDeContrat.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}la-rupture-de-contrat.svg`,
    path: PAGES.static.guideAlternantLaRuptureDeContrat.getPath(),
    updatedAt: "30/01/2026",
  },
  ["comprendre-la-remuneration"]: {
    id: "comprendre-la-remuneration",
    title: PAGES.static.guideAlternantComprendreLaRemuneration.title,
    description: PAGES.static.guideAlternantComprendreLaRemuneration.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}comprendre-la-remuneration.svg`,
    path: PAGES.static.guideAlternantComprendreLaRemuneration.getPath(),
    updatedAt: "30/01/2026",
  },
  ["apprentissage-et-handicap"]: {
    id: "apprentissage-et-handicap",
    title: PAGES.static.guideAlternantApprentissageEtHandicap.title,
    description: PAGES.static.guideAlternantApprentissageEtHandicap.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}apprentissage-et-handicap.svg`,
    path: PAGES.static.guideAlternantApprentissageEtHandicap.getPath(),
    updatedAt: "30/01/2026",
  },
  ["comment-signer-un-contrat-en-alternance"]: {
    id: "comment-signer-un-contrat-en-alternance",
    title: PAGES.static.guideAlternantCommentSignerUnContratEnAlternance.title,
    description: PAGES.static.guideAlternantCommentSignerUnContratEnAlternance.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}comment-signer-un-contrat-en-alternance.svg`,
    path: PAGES.static.guideAlternantCommentSignerUnContratEnAlternance.getPath(),
    updatedAt: "30/01/2026",
  },
  ["role-et-missions-du-maitre-d-apprentissage-ou-tuteur"]: {
    id: "role-et-missions-du-maitre-d-apprentissage-ou-tuteur",
    title: PAGES.static.guideAlternantRoleEtMissionsDuMaitreDApprentissageOuTuteur.title,
    description: PAGES.static.guideAlternantRoleEtMissionsDuMaitreDApprentissageOuTuteur.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}role-et-missions-du-maitre-d-apprentissage-ou-tuteur.svg`,
    path: PAGES.static.guideAlternantRoleEtMissionsDuMaitreDApprentissageOuTuteur.getPath(),
    updatedAt: "30/01/2026",
  },
  ["prevention-des-risques-professionnels-pour-les-apprentis"]: {
    id: "prevention-des-risques-professionnels-pour-les-apprentis",
    title: PAGES.static.guideAlternantPreventionDesRisquesProfessionnelsPourLesApprentis.title,
    description: PAGES.static.guideAlternantPreventionDesRisquesProfessionnelsPourLesApprentis.getMetadata().description,
    imageUrl: `${IMAGE_BASE_PATH}prevention-des-risques-professionnels-pour-les-apprentis.svg`,
    path: PAGES.static.guideAlternantPreventionDesRisquesProfessionnelsPourLesApprentis.getPath(),
    updatedAt: "30/01/2026",
  },
  ["simulateur"]: {
    id: "simulateur",
    title: "Je calcule ma rémunération",
    description: "Répondez à quelques questions pour connaître votre future rémunération en alternance",
    imageUrl: `${IMAGE_BASE_PATH}simulateur.svg`,
    path: PAGES.static.salaireAlternant.getPath(),
    updatedAt: "30/01/2026",
  },
}
