export const villeData = [
  {
    ville: "Bordeaux",
    slug: "bordeaux",
    geopoint: {
      lat: 44.837789,
      long: -0.57918,
    },
    content: {
      description_ville: {
        title: "capitale de la Nouvelle Aquitaine",
        text: "Bordeaux, est une <strong>destination de choix</strong> pour les alternants qui souhaitent allier études, carrière professionnelle et qualité de vie. Classée au patrimoine mondial de l'UNESCO, la ville séduit par son architecture du XVIIIe siècle, ses quais réaménagés le long de la Garonne et son dynamisme culturel. Avec près de <strong>800 000 habitants</strong> dans la métropole, Bordeaux offre un cadre urbain à taille humaine où il fait bon vivre. La ville a connu une transformation spectaculaire ces vingt dernières années, passant d'une cité portuaire endormie à une métropole moderne et attractive. Pour un alternant, Bordeaux représente l'équilibre parfait entre opportunités professionnelles dans des secteurs variés et vie étudiante animée, avec plus de <strong>100 000 étudiants</strong>. Le climat océanique doux, la proximité de l'océan Atlantique (à moins d'une heure) et le vignoble bordelais ajoutent un charme supplémentaire à cette destination. L'ambiance y est conviviale et moins stressante que dans les grandes métropoles comme Paris ou Lyon, tout en offrant des perspectives professionnelles comparables.",
        image: "bordeaux.png",
      },
      vie: {
        text: "Le tissu économique bordelais est diversifié et en pleine expansion, offrant de nombreuses opportunités pour les alternants. Le secteur du numérique et des nouvelles technologies est particulièrement dynamique, avec plus de 15 000 emplois dans l'IT et de nombreuses start-ups installées à Darwin, La Mêlée ou dans le quartier Euratlantique. L'aéronautique et le spatial constituent un pilier majeur avec des entreprises comme Dassault Aviation, Thalès et Safran qui recrutent régulièrement des alternants. Le secteur du vin et des spiritueux, emblématique de la région, propose des postes en marketing, commerce international et œnotourisme. La métropole accueille également de grandes entreprises dans le secteur bancaire (Crédit Agricole, CIC) et des assurances, ainsi qu'un pôle santé en développement avec le CHU et de nombreux laboratoires pharmaceutiques. Le commerce et le tourisme représentent aussi des viviers d'alternance importants. Les institutions publiques et les cabinets de conseil sont nombreux dans cette capitale régionale. Avec un taux de chômage inférieur à la moyenne nationale et une croissance démographique soutenue, Bordeaux attire de plus en plus d'entreprises nationales et internationales, créant ainsi un marché de l'alternance particulièrement favorable.",
        activites: [{ naf_label: "Activités culturelles et festives", rome_codes: ["R1203", "R1204"] }],
      },
      mobilite: {
        text: "Se déplacer à Bordeaux est facile et accessible grâce à un réseau de transports en commun performant géré par TBM (Transports Bordeaux Métropole). Le réseau compte quatre lignes de tramway (A, B, C et D) qui desservent l'ensemble de l'agglomération et constituent l'épine dorsale des déplacements urbains, avec une fréquence de passage élevée jusqu'à tard le soir. Les bus complètent efficacement ce réseau avec plus de 70 lignes régulières et des navettes électriques gratuites dans le centre-ville. L'abonnement mensuel TBM coûte environ 37 euros pour les moins de 26 ans, un tarif très avantageux pour les alternants. La ville est également très cyclable avec plus de 200 km de pistes cyclables, et le service V³ (Vcub) propose des vélos en libre-service à partir de 10 euros par mois. De nombreux alternants optent pour le vélo, particulièrement adapté au relief plat de la ville. Pour rejoindre les entreprises situées en périphérie, le réseau TransGironde assure des liaisons départementales. La gare Saint-Jean, desservie par TGV, permet de rejoindre Paris en 2h et les principales villes françaises. Enfin, Bordeaux dispose d'un aéroport international à Mérignac, accessible en 30 minutes en navette.",
        transports: ["Bus", "Tramway", "Pistes cyclables", "Trains régionaux et TGV", "Vélos en libre-service", "Aéroport"],
      },
      logement: {
        text: "Trouver un logement à Bordeaux nécessite une recherche active mais reste accessible pour les alternants avec un budget adapté. Pour un studio, comptez entre 450 et 650 euros charges comprises selon le quartier et l'état du bien, tandis qu'un T2 se situe généralement entre 600 et 850 euros. Les quartiers les plus prisés par les étudiants et alternants sont la Victoire, Saint-Michel et Capucins, offrant un bon rapport qualité-prix et une ambiance jeune et dynamique. Les Chartrons et Bacalan attirent ceux qui recherchent un cadre plus moderne et rénové, avec des loyers légèrement supérieurs. Bastide, sur la rive droite, propose des logements plus abordables avec un accès direct au centre-ville par le tram. Il est recommandé de commencer ses recherches au moins deux mois avant la rentrée sur les plateformes classiques (Leboncoin, PAP) et les groupes Facebook dédiés. Les résidences étudiantes privées constituent une alternative pratique mais souvent plus onéreuse (650-800 euros pour un studio meublé). N'oubliez pas que vous pouvez bénéficier des APL pour réduire votre loyer mensuel. Certains employeurs proposent également une aide au logement dans le cadre du contrat d'alternance, pensez à vous renseigner. La forte demande locative nécessite de constituer un dossier solide avec garants.",
        loyers: [
          { type: "Studio", price_range: "450 - 650 euros" },
          { type: "T2", price_range: "650 - 900 euros" },
        ],
      },
      loisir: {
        text: "Bordeaux offre une vie culturelle et festive particulièrement riche qui ravira les alternants en quête d'équilibre entre vie professionnelle et détente. Les quais de la Garonne, entièrement réaménagés, constituent le lieu de promenade et de rassemblement privilégié des Bordelais, idéal pour courir ou se retrouver entre amis. La Cité du Vin, monument architectural dédié aux cultures du vin, propose des expositions permanentes et des dégustations. Les nombreux bars et restaurants du quartier Saint-Pierre, Saint-Michel et des Chartrons animent les soirées, avec une ambiance étudiante particulièrement présente place de la Victoire et rue Saint-Rémi. Darwin, l'écosystème alternatif installé dans une ancienne caserne, accueille un skatepark, des food-trucks, des concerts et des événements éco-responsables. La ville compte plusieurs salles de concert (Rock School Barbey, I.Boat, Krakatoa) et théâtres pour tous les goûts musicaux. Les amateurs de culture peuvent profiter de nombreux musées (CAPC, Musée d'Aquitaine) et cinémas, dont plusieurs cinémas d'art et essai. Le sport est également accessible avec des infrastructures municipales nombreuses, des clubs associatifs et la proximité des plages du bassin d'Arcachon et des spots de surf de la côte atlantique. Les festivals rythment l'année, notamment Bordeaux Fête le Vin et Bordeaux Métropole.",
        types: ["Promenade", "Expositions", "Vie nocturne", "Culture alternative", "Concerts et théâtre", "Sports"],
      },
    },
  },
  {
    ville: "Lyon",
    slug: "lyon",
    geopoint: {
      lat: 45.764043,
      long: 4.835659,
    },
    content: {
      main: {
        title: "Trouver une alternance à Lyon",
        text: "Lyon, troisième métropole de France, offre un cadre exceptionnel pour débuter votre carrière en alternance. Avec plus de 170 000 étudiants et un tissu économique diversifié, la capitale des Gaules regorge d’opportunités dans les biotechnologies, le digital, la banque et l’industrie. Les entreprises comme Sanofi, BioMérieux, Renault Trucks ou encore les startups de Lyon French Tech recrutent activement des alternants. Située à seulement 2h de Paris en TGV, Lyon combine dynamisme économique et qualité de vie exceptionnelle. Entre son patrimoine UNESCO, sa gastronomie renommée et ses nombreux événements culturels, vous profiterez d’un environnement stimulant pour vos études et votre vie personnelle. Le réseau TCL facilite vos déplacements quotidiens à tarif réduit. Lyon est définitivement la ville idéale pour réussir votre formation en alternance.",
        image: "lyon-alternance-place-bellecour.jpg",
      },
      description_ville: {
        title: "Lyon, capitale de la gastronomie et métropole dynamique",
        subtitle: "",
        text: "Lyon, avec ses 522 000 habitants et sa métropole de 1,4 million d’habitants, se positionne comme la troisième ville de France et un pôle économique majeur. Capitale historique de la région Auvergne-Rhône-Alpes, elle accueille près de 170 000 étudiants répartis dans trois universités et de prestigieuses grandes écoles comme l’INSA Lyon, l’École Centrale ou EM Lyon. Son économie diversifiée s’appuie sur des secteurs d’excellence comme les biotechnologies et la pharmacie avec des leaders mondiaux tels que Sanofi et BioMérieux, le digital avec l’écosystème Lyon French Tech, la banque et l’assurance, la chimie de pointe, ainsi que la logistique et l’industrie manufacturière. Classée au patrimoine mondial de l’UNESCO, Lyon est également réputée pour sa gastronomie exceptionnelle, ses bouchons typiques et son art de vivre. Idéalement située entre les Alpes et la Méditerranée, au confluent du Rhône et de la Saône, la ville bénéficie d’une position géographique stratégique qui en fait un carrefour européen incontournable pour les entreprises et les talents.",
        data: null,
      },
      opportunite_emploi: {
        text: "Le marché de l’emploi en alternance à Lyon est particulièrement dynamique et diversifié, offrant des perspectives exceptionnelles aux jeunes en formation. Le secteur des biotechnologies et de la santé constitue un pilier majeur avec des entreprises comme Sanofi Pasteur, BioMérieux, Boiron et Merial qui proposent régulièrement des contrats d’alternance dans la recherche, la production et la qualité. L’écosystème Lyon French Tech, l’un des plus importants de France, génère de nombreuses opportunités dans le développement web, la data science, la cybersécurité et le marketing digital au sein de startups innovantes et de scale-ups. Le secteur bancaire et assurantiel, avec des sièges régionaux de Société Générale, LCL, April et de nombreuses mutuelles, recrute des alternants en finance, gestion de patrimoine et relation client. L’industrie manufacturière reste forte avec Renault Trucks, le Groupe SEB et de nombreux équipementiers qui recherchent des profils techniques en ingénierie, maintenance et supply chain. La chimie, à travers le pôle Axel’One, et la logistique, favorisée par la position stratégique de Lyon, complètent ce paysage économique. Les PME et ETI, très nombreuses dans la région, offrent également d’excellentes opportunités d’apprentissage dans tous les domaines, du commerce à la communication en passant par les ressources humaines. Cette diversité sectorielle garantit aux alternants de trouver des postes adaptés à leur profil, quel que soit leur niveau d’études, du BTS au diplôme d’ingénieur ou d’école de commerce.",
      },
      mobilite: {
        text: "Se déplacer à Lyon en tant qu’alternant est particulièrement simple et économique grâce au réseau TCL (Transports en Commun Lyonnais) qui comprend 4 lignes de métro, 7 lignes de tramway, 2 funiculaires et un vaste réseau de bus couvrant toute la métropole. Les jeunes de moins de 26 ans bénéficient d’un tarif préférentiel avec l’abonnement Jeune à environ 36 euros par mois, permettant des déplacements illimités. Le service Vélo’v, avec ses nombreuses stations réparties dans toute la ville, propose une alternative écologique pour environ 35 euros par an. Lyon Part-Dieu, principale gare TGV, vous connecte à Paris en seulement 2 heures, à Marseille en 1h45 et aux principales villes européennes. L’aéroport Lyon-Saint-Exupéry, accessible en 30 minutes via le Rhônexpress, offre des liaisons nationales et internationales. Concernant le logement, comptez entre 450 et 650 euros pour un studio et entre 650 et 900 euros pour un T2, avec des variations selon les quartiers. La Guillotière, multiculturelle et dynamique, la Croix-Rousse au charme bohème, Gerland avec ses infrastructures modernes et Villeurbanne, plus abordable et très étudiante, sont des quartiers particulièrement adaptés aux alternants. Pour financer votre logement, vous pouvez bénéficier des aides au logement comme l’APL, du dispositif Action Logement pour l’avance de dépôt de garantie, et de Visale qui propose une caution gratuite pour les moins de 30 ans. La Métropole de Lyon propose également des programmes d’accompagnement spécifiques pour faciliter l’accès au logement des jeunes en formation.",
      },
      loisir: {
        text: "Lyon offre une vie culturelle et festive exceptionnelle qui séduira tous les alternants en quête d’équilibre entre travail et loisirs. Le patrimoine culturel est remarquable avec le Musée des Beaux-Arts, l’un des plus riches de France, le Musée des Confluences dédié aux sciences et aux sociétés, et l’Institut Lumière qui célèbre la naissance du cinéma dans la ville des frères Lumière. Les amateurs de spectacles vivants apprécieront l’Opéra National de Lyon, les Nuits de Fourvière qui transforment le théâtre antique en scène magique chaque été, et la Maison de la Danse réputée internationalement. La Presqu’île, cœur battant de Lyon entre Rhône et Saône, concentre boutiques, restaurants et bars branchés, tandis que les Pentes de la Croix-Rousse offrent une ambiance alternative avec leurs fresques murales, leurs boutiques créatives et leurs bars animés. Le Vieux Lyon, avec ses traboules mystérieuses et ses bouchons traditionnels, permet de découvrir l’authentique gastronomie lyonnaise. Les berges du Rhône et du parc de la Tête d’Or, poumon vert de 115 hectares, sont parfaits pour le jogging, le vélo ou simplement se détendre entre amis. Le quartier de la Confluence, ultra-moderne, abrite Le Sucre, club électro incontournable, et Le Transbordeur pour les concerts. Lyon vibre au rythme d’événements majeurs comme la Fête des Lumières en décembre qui attire des millions de visiteurs, Nuits Sonores pour les amateurs de musique électronique, et la Biennale de la Danse. Les Halles de Lyon Paul Bocuse raviront les gourmets, tandis que les nombreux cinémas, dont le Comoedia art et essai, satisferont les cinéphiles. Pour les sportifs, les Alpes sont à moins de deux heures pour le ski l’hiver, et les massifs du Beaujolais et du Pilat offrent de superbes randonnées. Cette richesse culturelle et la douceur de vivre lyonnaise font de la ville un cadre idéal pour s’épanouir pendant vos années d’alternance.",
      },
    },
  },
]
