export const NBR_EXPIRATION_J7 = 7
export const AUTHTYPE = {
  OPCO: "OPCO",
  CFA: "CFA",
  ENTREPRISE: "ENTREPRISE",
  ADMIN: "ADMIN",
}
export const USER_STATUS = {
  ACTIVE: "VALIDÉ",
  WAITING: "EN ATTENTE DE VALIDATION",
  DISABLED: "DESACTIVÉ",
}
