export enum BusinessErrorCodes {
  IS_CFA = "IS_CFA",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  CLOSED = "CLOSED",
  NON_DIFFUSIBLE = "NON_DIFFUSIBLE",
  UNKNOWN = "UNKNOWN",
  UNSUPPORTED = "UNSUPPORTED",
  NOT_QUALIOPI = "NOT_QUALIOPI",
}
