export enum BusinessErrorCodes {
  IS_CFA = "IS_CFA",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  CLOSED = "CLOSED",
  NON_DIFFUSIBLE = "NON_DIFFUSIBLE",
  UNKNOWN = "UNKNOWN",
  UNSUPPORTED = "UNSUPPORTED",
  NOT_QUALIOPI = "NOT_QUALIOPI",
  TOO_MANY_APPLICATIONS_PER_DAY = "TOO_MANY_APPLICATIONS_PER_DAY",
  TOO_MANY_APPLICATIONS_PER_OFFER = "TOO_MANY_APPLICATIONS_PER_OFFER",
  TOO_MANY_APPLICATIONS_PER_SIRET = "Vous avez atteint le quota maximum de candidatures pour ce SIRET",
}
