import { z } from "zod"

// Define reusable schemas for common property types
const stringSchema = z.string()
const booleanSchema = z.boolean()
const dateSchema = z.date()

// Define schemas for nested objects
const geoCoordSchema = stringSchema

// Define schemas for each interface
const etablissementFormateurSchema = {
  etablissement_formateur_id: stringSchema,
  etablissement_formateur_siret: stringSchema,
  etablissement_formateur_enseigne: stringSchema,
  etablissement_formateur_uai: stringSchema,
  etablissement_formateur_type: stringSchema,
  etablissement_formateur_conventionne: stringSchema,
  etablissement_formateur_declare_prefecture: stringSchema,
  etablissement_formateur_datadock: stringSchema,
  etablissement_formateur_adresse: stringSchema,
  etablissement_formateur_code_postal: stringSchema,
  etablissement_formateur_code_commune_insee: stringSchema,
  etablissement_formateur_localite: stringSchema,
  etablissement_formateur_complement_adresse: stringSchema,
  etablissement_formateur_cedex: stringSchema,
  etablissement_formateur_entreprise_raison_sociale: stringSchema,
  geo_coordonnees_etablissement_formateur: geoCoordSchema,
  etablissement_formateur_region: stringSchema,
  etablissement_formateur_num_departement: stringSchema,
  etablissement_formateur_nom_departement: stringSchema,
  etablissement_formateur_nom_academie: stringSchema,
  etablissement_formateur_num_academie: stringSchema,
  etablissement_formateur_siren: stringSchema,
  etablissement_formateur_courriel: stringSchema,
  etablissement_formateur_published: booleanSchema,
  etablissement_formateur_catalogue_published: booleanSchema,
  rncp_etablissement_formateur_habilite: booleanSchema,
  etablissement_formateur_date_creation: dateSchema,
}

const etablissementGestionnaireSchema = {
  etablissement_gestionnaire_id: stringSchema,
  etablissement_gestionnaire_siret: stringSchema,
  etablissement_gestionnaire_enseigne: stringSchema,
  etablissement_gestionnaire_uai: stringSchema,
  etablissement_gestionnaire_type: stringSchema,
  etablissement_gestionnaire_conventionne: stringSchema,
  etablissement_gestionnaire_declare_prefecture: stringSchema,
  etablissement_gestionnaire_datadock: stringSchema,
  etablissement_gestionnaire_adresse: stringSchema,
  etablissement_gestionnaire_code_postal: stringSchema,
  etablissement_gestionnaire_code_commune_insee: stringSchema,
  etablissement_gestionnaire_localite: stringSchema,
  etablissement_gestionnaire_complement_adresse: stringSchema,
  etablissement_gestionnaire_cedex: stringSchema,
  etablissement_gestionnaire_entreprise_raison_sociale: stringSchema,
  geo_coordonnees_etablissement_gestionnaire: geoCoordSchema,
  etablissement_gestionnaire_region: stringSchema,
  etablissement_gestionnaire_num_departement: stringSchema,
  etablissement_gestionnaire_nom_departement: stringSchema,
  etablissement_gestionnaire_nom_academie: stringSchema,
  etablissement_gestionnaire_num_academie: stringSchema,
  etablissement_gestionnaire_siren: stringSchema,
  etablissement_gestionnaire_courriel: stringSchema,
  etablissement_gestionnaire_published: booleanSchema,
  etablissement_gestionnaire_catalogue_published: booleanSchema,
  rncp_etablissement_gestionnaire_habilite: booleanSchema,
  etablissement_gestionnaire_date_creation: dateSchema,
}

const etablissementReferenceSchema = {
  etablissement_reference: stringSchema,
  etablissement_reference_published: booleanSchema,
  etablissement_reference_habilite_rncp: booleanSchema,
  etablissement_reference_certifie_qualite: booleanSchema,
  etablissement_reference_date_creation: dateSchema,
}

// Define a schema for a single string or an array of strings
const stringOrArraySchema = z.union([z.string(), z.array(z.string())])

// Define the Zod schema for IFormationCatalogue
export const zFormationCatalogueSchema = z
  .object({
    _id: z.string(),
    cle_ministere_educatif: z.string(),
    cfd: z.string(),
    cfd_specialite: z.record(z.unknown()), // Assuming cfd_specialite is an object
    cfa_outdated: z.boolean(),
    cfd_date_fermeture: z.date(),
    cfd_entree: z.string(),
    mef_10_code: z.string(),
    mefs_10: z.array(z.string()),
    nom_academie: z.string(),
    num_academie: z.string(),
    code_postal: z.string(),
    code_commune_insee: z.string(),
    num_departement: z.string(),
    nom_departement: z.string(),
    region: z.string(),
    localite: z.string(),
    uai_formation: z.string(),
    nom: z.string(),
    intitule_long: z.string(),
    intitule_court: z.string(),
    diplome: z.string(),
    niveau: z.string(),
    onisep_url: z.string(),
    onisep_intitule: z.string(),
    onisep_libelle_poursuite: z.string(),
    onisep_lien_site_onisepfr: z.string(),
    onisep_discipline: z.string(),
    onisep_domaine_sousdomaine: z.string(),
    rncp_code: z.string(),
    rncp_intitule: z.string(),
    rncp_eligible_apprentissage: z.boolean(),
    rncp_details: z.record(z.unknown()), // Assuming rncp_details is an object
    rome_codes: z.array(z.string()),
    capacite: z.string(),
    duree: z.string(),
    annee: z.string(),
    email: z.string(),
    parcoursup_statut: z.string(),
    parcoursup_error: z.string(),
    parcoursup_statut_history: z.array(z.record(z.unknown())),
    parcoursup_reference: z.boolean(),
    parcoursup_a_charger: z.boolean(),
    parcoursup_id: z.string(),
    affelnet_reference: z.boolean(),
    affelnet_a_charger: z.boolean(),
    affelnet_statut: z.string(),
    affelnet_statut_history: z.array(z.record(z.unknown())),
    source: z.string(),
    commentaires: z.string(),
    opcos: z.array(z.string()),
    info_opcos: z.number(),
    info_opcos_intitule: z.string(),
    published: z.boolean(),
    rco_published: z.boolean(),
    draft: z.boolean(),
    created_at: z.date(),
    updates_history: z.array(z.record(z.unknown())),
    last_update_at: z.date(),
    last_update_who: z.string(),
    to_update: z.boolean(),
    update_error: z.string(),
    lieu_formation_geo_coordonnees: z.string(),
    lieu_formation_adresse: z.string(),
    lieu_formation_adresse_computed: z.string(),
    lieu_formation_siret: z.string(),
    id_rco_formation: z.string(),
    id_formation: z.string(),
    id_action: z.string(),
    ids_action: z.array(z.string()),
    id_certifinfo: z.string(),
    tags: z.array(z.string()),
    libelle_court: stringOrArraySchema,
    niveau_formation_diplome: z.string(),
    affelnet_infos_offre: z.string(),
    affelnet_code_nature: z.string(),
    affelnet_secteur: z.string(),
    affelnet_raison_depublication: z.string(),
    bcn_mefs_10: z.array(z.record(z.unknown())), // Assuming bcn_mefs_10 is an object array
    editedFields: z.record(z.unknown()), // Assuming editedFields is an object
    parcoursup_raison_depublication: z.string(),
    distance_lieu_formation_etablissement_formateur: z.number(),
    niveau_entree_obligatoire: z.number(),
    entierement_a_distance: z.boolean(),
    catalogue_published: z.boolean(),
    contenu: z.string(),
    objectif: z.string(),
    date_debut: z.array(z.date()),
    date_fin: z.array(z.date()),
    modalites_entrees_sorties: z.array(z.boolean()),
  })
  .extend(etablissementFormateurSchema)
  .extend(etablissementGestionnaireSchema)
  .extend(etablissementReferenceSchema)
