x-default: &default
  deploy:
    resources:
      limits:
        memory: 1.5g
  restart: always
  networks:
    - mna_network

name: "lba_preview_{{pr_number}}"

services:
  server:
    <<: *default
    image: "ghcr.io/mission-apprentissage/mna_lba_server:0.0.0-{{pr_number}}"
    container_name: lba_{{pr_number}}_server
    environment:
      - VIRTUAL_HOST={{pr_number}}.labonnealternance-preview.apprentissage.beta.gouv.fr
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST={{pr_number}}.labonnealternance-preview.apprentissage.beta.gouv.fr
      - LETSENCRYPT_EMAIL=misson.apprentissage.devops@gmail.com
    volumes:
      - server:/data
      - ./.env_server:/app/server/.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 11
      start_period: 10s
    labels:
      - autoheal=true

  ui:
    <<: *default
    image: "ghcr.io/mission-apprentissage/mna_lba_ui:0.0.0-{{pr_number}}-preview"
    container_name: lba_{{pr_number}}_ui
    env_file: .env_ui
    environment:
      - VIRTUAL_HOST={{pr_number}}.labonnealternance-preview.apprentissage.beta.gouv.fr
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST={{pr_number}}.labonnealternance-preview.apprentissage.beta.gouv.fr
      - LETSENCRYPT_EMAIL=misson.apprentissage.devops@gmail.com

  jobs_processor:
    <<: *default
    image: "ghcr.io/mission-apprentissage/mna_lba_server:0.0.0-{{pr_number}}"
    container_name: lba_{{pr_number}}_jobs_processor
    command: ["yarn", "cli", "job_processor:start"]
    volumes:
      - server:/data
      - ./.env_server:/app/server/.env

volumes:
  server:

networks:
  mna_network:
    name: mna_network
    external: true
