export { DATE_DERNIERE_MISE_A_JOUR, DATE_FIN_EXONERATION_CHARGES_APPRENTISSAGE, MAX_DATE_NAISSANCE, MIN_DATE_NAISSANCE, MIN_DEBUT_CONTRAT, NEXT_START_OF_MONTH } from "./dates"
export { SMIC } from "./smic"
export {
  TAUX_COTISATIONS_SALARIALES_AVANT_EXONERATION_APPRENTISSAGE_PRIVE,
  TAUX_COTISATIONS_SALARIALES_AVANT_EXONERATION_APPRENTISSAGE_PUBLIC,
  TAUX_COTISATIONS_SALARIALES_CONTRAT_PROFESSIONNALISATION,
  TAUX_EXONERATION_CHARGES_SALARIALES_APPRENTISSAGE_PUBLIC,
} from "./taux-de-cotisation"
export type { AnneeContrat, NiveauDiplomeGroup, TrancheAge } from "./taux-smic"
export { NIVEAU_DIPLOME_TO_GROUP, TAUX_APPRENTISSAGE, TAUX_PROFESSIONNALISATION, TRANCHES_AGE_APPRENTISSAGE, TRANCHES_AGE_PROFESSIONNALISATION } from "./taux-smic"
