export { DATE_DERNIERE_MISE_A_JOUR, DATE_FIN_EXONERATION_CHARGES_APPRENTISSAGE } from "./dates"

export {
  TAUX_COTISATIONS_SALARIALES_AVANT_EXONERATION_APPRENTISSAGE_PRIVE,
  TAUX_COTISATIONS_SALARIALES_AVANT_EXONERATION_APPRENTISSAGE_PUBLIC,
  TAUX_EXONERATION_CHARGES_SALARIALES_APPRENTISSAGE_PUBLIC,
  TAUX_COTISATIONS_SALARIALES_CONTRAT_PROFESSIONNALISATION,
} from "./taux-de-cotisation"

export type { TrancheAge, AnneeContrat, NiveauDiplomeGroup } from "./taux-smic"

export { TRANCHES_AGE_APPRENTISSAGE, TRANCHES_AGE_PROFESSIONNALISATION, TAUX_APPRENTISSAGE, TAUX_PROFESSIONNALISATION, NIVEAU_DIPLOME_TO_GROUP } from "./taux-smic"

export { SMIC } from "./smic"
