export type {
  ILbaItemCompany,
  ILbaItemCompanyHQ,
  ILbaItemContact,
  ILbaItemFormation,
  ILbaItemFtJob,
  ILbaItemJob,
  ILbaItemLbaCompany,
  ILbaItemLbaJob,
  ILbaItemNaf,
  ILbaItemOpco,
  ILbaItemPlace,
  ILbaItemRome,
  ILbaItemTraining,
  ILbaItemTrainingSession,
} from "shared/models/lbaItem.model"
