export const emailStatus = {
  request: "Envoyé",
  delivered: "Délivré",
  unique_opened: "1ère ouverture",
  opened: "Connu ouvert",
  proxy_open: "Chargé par proxy",
  click: "Cliqué",
  soft_bounce: "Soft Bounce",
  hard_bounce: "Hard Bounce",
  invalid_email: "Email invalide",
  error: "Erreur",
  deferred: "Différé",
  spam: "Plainte",
  unsubscribed: "Désinscrit",
  blocked: "Bloqué",
};
