#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint-staged
yarn workspace server tsoa
git add server/src/generated server/static/generated
./.husky/preventSensibleFilesCommit.sh
yarn node-talisman --githook pre-commit
